# 5.1 pandas 数据结构介绍

## 5.1.1 Series

In [1]:
import pandas as pd

In [2]:
from pandas import Series, DataFrame

In [3]:
obj = pd.Series([4, 7, -5, 3])

In [4]:
#索引在左，值在右
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
# 可以通过 values 属性获得Series对象的值
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
# 可以通过 index 属性获得Series对象的值
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
#创建一个索引序列，用标签标识每个数据点
obj2 = pd.Series([4, 7, -5, 3], index = ['d', 'b', 'a', 'c'])

In [8]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2 = pd.Series([4, 7, -5, 3], ['d', 'b', 'a', 'c'])

In [10]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [11]:
## obj2.index

In [12]:
obj2['a']

-5

In [13]:
obj2[['c', 'a', 'd']]
# ['c', 'a', 'd'] 作为索引列表

c    3
a   -5
d    4
dtype: int64

In [14]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [15]:
obj2 * 2

d     8
b    14
a   -10
c     6
dtype: int64

In [16]:
'b' in obj2

True

In [17]:
# 用字典生成一个 Series
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [18]:
obj3 = pd.Series(sdata)

In [19]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [20]:
# 可以将dictionary的key按照所想要的顺序传递给构造函数
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [21]:
obj4 = pd.Series(sdata, states)

In [22]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [23]:
# isnull 和 notnull函数来检查缺失数据

In [24]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [25]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [26]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [27]:
# Series的自动对齐属性

In [28]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [29]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [30]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [31]:
# Series 对象自身及其索引都有name属性

In [32]:
obj4.name = 'population'
obj4.index.name = 'state'

In [33]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [34]:
# Series 的索引按位置赋值

In [35]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [36]:
obj.index = ['Bob','Steve','Jeff','Ryan']

In [37]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

## 5.1.2 DataFrame

In [38]:
# 等长度列表构建DataFrame

In [39]:
data = {'state': ['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [40]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [41]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [42]:
pd.DataFrame(data, columns = ['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [43]:
# 如果传的列不包含在字典中，将会出现缺失值
frame2 = pd.DataFrame(data, columns = ['year','state','pop','debt'], index = ['one','two','three','four','five','six'])

In [44]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [45]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [46]:
# DataFrame中的一列， 可以检索为Series

In [47]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [48]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [49]:
# DataFrame中的一行， 可以loc进行选取

In [50]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [51]:
# 给列赋值

In [52]:
frame2['debt'] = 16.5

In [53]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [54]:
# 将 Series 赋值给一列

In [55]:
val = pd.Series([-1.2, -1.5, -1.7], ['two', 'four', 'five'])

In [56]:
frame2['debt'] = val

In [57]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [58]:
del frame2['debt']

In [59]:
frame2

year   state  pop
one    2000    Ohio  1.5
two    2001    Ohio  1.7
three  2002    Ohio  3.6
four   2001  Nevada  2.4
five   2002  Nevada  2.9
six    2003  Nevada  3.2

In [60]:
# nested dictionary

In [61]:
pop = {'Nevada': {2011: 2.4, 2022: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [62]:
frame3 = pd.DataFrame(pop)

In [63]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     NaN   1.7
2002     NaN   3.6
2011     2.4   NaN
2022     2.9   NaN

In [64]:
# 转置

In [65]:
frame3.T

2000  2001  2002  2011  2022
Nevada   NaN   NaN   NaN   2.4   2.9
Ohio     1.5   1.7   3.6   NaN   NaN

## 5.1.3 索引对象

In [66]:
obj = pd.Series(range(3), index = ['a', 'b', 'c'])

In [67]:
index = obj.index

In [68]:
index

Index(['a', 'b', 'c'], dtype='object')

In [69]:
# 索引对象是不可变的
index[1] = 'd'

TypeError: Index does not support mutable operations

# 5.2 基本功能

## 5.2.1 reindex

In [ ]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], ['d', 'b', 'a', 'c'])

In [ ]:
obj

In [ ]:
obj2 = obj.reindex(['a','b','c','d','e'])

In [ ]:
obj2

## 5.2.2 drop

In [70]:
import numpy as np

In [71]:
obj = pd. Series(np.arange(5.), index = ['a', 'b', 'c', 'd', 'e'])

In [72]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [73]:
new_obj = obj.drop('c')

In [74]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

## 5.2.3 索引，选择与过滤

In [ ]:
#Series 的index可以不仅仅是整数

In [75]:
obj = pd.Series(np.arange(4.), index = ['a', 'b', 'c', 'd'])

In [76]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [77]:
obj['b']

1.0

In [78]:
obj[1]

1.0

In [79]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [81]:
# 普通的Python切片是不包含尾部的， Series的切片与之不同
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [82]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [83]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)), 
                    index = ['Ohio','Colorado','Utah','New York'], 
                    columns = ['one','two','three','four'])

In [84]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [85]:
# 索引column
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [86]:
data[['two', 'three']]

two  three
Ohio        1      2
Colorado    5      6
Utah        9     10
New York   13     14

In [87]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [89]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### 5.2.3.1 loc 和 iloc 从DataFrame中选出数组行和列的子集

In [93]:
#轴标签 loc

In [94]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [95]:
#整数标签 iloc

In [99]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [98]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

## 5.2.4 整数索引

## 5.2.5 算术和数据对齐

In [100]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5],index = ['a','c','d','e'])

In [101]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index = ['a','c','e','f','g'])

In [102]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [103]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [105]:
#没有交叠的标签位置上，内部数据对齐会产生缺失值。缺失值会在后续的算术操作上产生影响。
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

### 5.2.5.1 使用填充值的算术方法

In [111]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns = list('abcd'))

In [112]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns = list('abcde'))

In [113]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [114]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [116]:
#不重叠的位置会出现NaN
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [117]:
#在df1上使用add方法，将df2和一个fill_value作为参数传入

In [118]:
df1.add(df2, fill_value = 0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

### 5.2.5.1 DataFrame 和 Series之间的操作

In [119]:
arr = np.arange(12.).reshape((3, 4))

In [120]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [121]:
arr[0]

array([0., 1., 2., 3.])

In [123]:
# “广播机制”
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

## 5.2.6 函数应用和映射

## 5.2.7 排序和排名

In [124]:
# sort_index()
# sort_values()

## 5.2.8 含有重复标签的轴索引

In [125]:
# index.is_unique

# 5.3 描述性统计的概述和计算